<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <SupportedOSPlatformVersion>28.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <ApplicationId>com.rdpvault.app</ApplicationId>
    <ApplicationVersion>3</ApplicationVersion>
    <ApplicationDisplayVersion>2.0.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot Condition="'$(Configuration)' == 'Release'">true</AndroidEnableProfiledAot>
    <RootNamespace>RDPVault.Android</RootNamespace>
    <RuntimeIdentifiers>android-arm64;android-arm;android-x64</RuntimeIdentifiers>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NETSDK1202;XA0141</WarningsNotAsErrors>
    <NoWarn>$(NoWarn);CA1422;CA1416;CS0067;CS0414</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and Exists('$(MSBuildThisFileDirectory)rdpvault-release.keystore')">
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidSigningKeyStore>$(MSBuildThisFileDirectory)rdpvault-release.keystore</AndroidSigningKeyStore>
    <AndroidSigningStorePass>RdpVaultReleasePass2026!</AndroidSigningStorePass>
    <AndroidSigningKeyAlias>rdpvault</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>RdpVaultReleasePass2026!</AndroidSigningKeyPass>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RDPVault.Core\RDPVault.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Android" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <PackageReference Include="Xamarin.AndroidX.Biometric" Version="1.1.0.33" />
  </ItemGroup>

  <ItemGroup>
    <AndroidNativeLibrary Abi="arm64-v8a" Include="lib\arm64-v8a\*.so" />
    <AndroidNativeLibrary Abi="x86_64" Include="lib\x86_64\*.so" />
  </ItemGroup>
</Project>
